"""Property-suite codegen (plan C-13): oracle-bound Hypothesis tests.

The oracle import is mandatory: predicate terms resolve to the contract-side
oracle artifact, never to the producer module (VERIFIED-DESIGNS D-CG).

Runtime contract (F2 close, 2026-09-12): Hypothesis IS the top-level forall —
a compiled `(all_([names], lambda params: BODY))` renders as an assertion of
BODY under @given, never as a call to an `all_` runtime. Soundness of the
elision is the caller's to supply: the binders passed in `spec.binders` must
quantify the same universe the clause's forall claims (the oracle campaign
draws each spec's own domains via st.sampled_from; an unbounded convention
strategy would assert a stronger universal than the clause states). A
quantifier below the top level (top-level exists, nested forall) has no
defined runtime in a suite and renders as a typed StrategyError, not a
NameError on first draw. `member_of` is suite-owned (emitted as a two-line
shim) unless the oracle exports it itself.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from zft.dsl.predicate import DSL_VERSION
from zft.dsl.strategies import StrategyError, strategy_for

HEADER = '"""Generated by zft — clause {alias}. Do not edit."""'

# The exact shape compile_predicate emits for a leading `forall a, b:`:
# bound-list repr, lambda params, body. The greedy body keeps every inner
# closing paren; the anchor is the wrapper's own final two.
_TOPLEVEL_FORALL_RE = re.compile(
    r"^\(all_\(\[(?P<bound>[^]]+)\], lambda (?P<params>[^:]+): (?P<body>.+)\)\)$"
)


@dataclass
class PropertyTestSpec:
    alias: str
    predicate_py: str
    binders: dict[str, str]  # binder name -> strategy expression
    oracle_src: str
    oracle_symbols: list[str]
    producer_imports: str
    examples: int = 200


def elide_top_level_forall(predicate_py: str) -> str:
    """Strip the compiled top-level `forall` wrapper: @given is the quantifier.

    Returns the predicate unchanged when it does not open with a forall. A
    quantifier surviving below the top level raises StrategyError — the old
    renderer emitted it raw and the suite died of `NameError: all_` on its
    first draw (campaign finding F2).
    """
    m = _TOPLEVEL_FORALL_RE.match(predicate_py)
    if m is None:
        body = predicate_py
    else:
        params = [p.strip() for p in m.group("params").split(",")]
        bound = [b.strip().strip("'\"") for b in m.group("bound").split(",")]
        if params != bound:  # the wrapper is machine-made; divergence is drift
            raise StrategyError(
                f"compiled forall binders {bound} disagree with lambda "
                f"params {params} in: {predicate_py}"
            )
        body = m.group("body")
    if re.search(r"\ball_\(", body):
        raise StrategyError(
            "quantifier below the top level has no runtime in a generated "
            "property suite (v1): forall binds through @given, and nested "
            "forall/exists cannot be executed — narrow the clause or own a "
            "quantifier runtime first"
        )
    return body


def render_property_test(spec: PropertyTestSpec) -> str:
    fn = re.sub(r"\W", "_", spec.alias)
    binders = ", ".join(f"{name}={strategy}" for name, strategy in spec.binders.items())
    param_list = ", ".join(spec.binders)
    body = elide_top_level_forall(spec.predicate_py)
    lines = [
        HEADER.format(alias=spec.alias),
        f"# DSL_VERSION: {DSL_VERSION}",
        "from hypothesis import given, settings, strategies as st",
        "",
        "",
        spec.producer_imports,
    ]
    # campaign F2b: a clause with no oracle-owned symbols (pure arithmetic,
    # binder-only existentials) must not emit a bare `from oracle import ` —
    # that is a SyntaxError in the rendered suite
    if sorted(spec.oracle_symbols):
        lines.append(f"from oracle import {', '.join(sorted(spec.oracle_symbols))}")
    if "member_of(" in body and "member_of" not in set(spec.oracle_symbols):
        lines += [
            "",
            "",
            "def member_of(item, container):",
            "    return item in container",
        ]
    lines += [
        "",
        "",
        f"@settings(max_examples={spec.examples}, deadline=None, derandomize=True, print_blob=True)",  # noqa: E501
        f"@given({binders})",
        f"def test_{fn}({param_list}):",
        f'    assert {body}, "CONTRACT VIOLATED: {spec.alias}"',
        "",
    ]
    return "\n".join(lines)


def binder_strategies(predicate_py: str, check: dict) -> dict[str, str]:
    """Extract binder names from compiled quantifier lambda signature and map strategies."""
    import re

    m = re.search(r"all_\(\[([^\]]+)\]", predicate_py)
    if not m:
        raise StrategyError("predicate has no quantifier binders — not a property clause")
    names = [s.strip().strip("'\"") for s in m.group(1).split(",")]
    return {name: strategy_for(name, check) for name in names}
